### ISSUE TITLE
[Feat] 2차 과제

### ISSUE THREAD

**Issue by meltsplit** [31st-IN-SOPT-iOS-Part/SeokWooJang#4]
## 🛠 Issue
- 2차 과제 구현하기

## 📋 To-do

- [x] Auth 뷰에 Auto Layout 적용하기
- [x] 프로필뷰 UI 구현하기
- [x] 화면 전환 구현하기
