### ISSUE TITLE
[Feat] 3차 과제

### ISSUE THREAD

**Issue by meltsplit** [31st-IN-SOPT-iOS-Part/SeokWooJang#6]
## 🛠 Issue
- 3차 과제 구현하기
- 금잔디조 코드리뷰하기
- 흥미로웠던 코드 복기 및 아티클 작성

## 📋 To-do
- [x] 친구뷰 TabeView 구현하기
- [x] 채팅뷰 CollectionView 구현하기
- [x] 갤러리 CollectionView 구현하기
- [x] UISwipeActionConfiguration 구현하기
- [x] 갤러리 CollectionView 인덱싱 로직 구현하기
